### ISSUE TITLE
Windows failure on fresh install (without wordlist installed)

### ISSUE THREAD

**Issue by mdvthu** [mdvthu/mempw#6]
```
mempw
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\Scripts\mempw-script.py", line 33, in <module>
    sys.exit(load_entry_point('mempw==0.1.3', 'console_scripts', 'mempw')())
  File "C:\Users\username\AppData\Local\Programs\Python\Python39\Scripts\mempw-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\users\username\appdata\local\programs\python\python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "c:\users\username\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\mempw\__init__.py", line 1, in <module>
    from .core import new_password  # noqa: F401
  File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\mempw\core.py", line 24, in <module>
    words = wordlist.words()
  File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\mempw\wordlist.py", line 65, in words
    _create_cache()
  File "c:\users\username\appdata\local\programs\python\python39\lib\site-packages\mempw\wordlist.py", line 27, in _create_cache
    os.mkdir(dir_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\username\\AppData\\Local\\mdvthu\\mempw\\Cache'
```

**Comment by mdvthu** [comment]
Fixed with commit 39cca9cbe4c85ebc49d541c0244e8d8ed5bea03d
